[colors]
name = "Seoul256"
author = ""
variant = ""
color_01 = "#4e4e4e"
color_02 = "#d68787"
color_03 = "#5f865f"
color_04 = "#d8af5f"
color_05 = "#85add4"
color_06 = "#d7afaf"
color_07 = "#87afaf"
color_08 = "#d0d0d0"
color_09 = "#626262"
color_10 = "#d75f87"
color_11 = "#87af87"
color_12 = "#ffd787"
color_13 = "#add4fb"
color_14 = "#ffafaf"
color_15 = "#87d7d7"
color_16 = "#e4e4e4"
background = "#3a3a3a"
foreground = "#d0d0d0"
cursor = "#d0d0d0"
